name: messenger
description: Flutter Messenger Clean Architecture with Bloc, Cubit, Provider, RxDart, ObjectBox, SharedPreferences, Retrofit, Dio, GetIt(Dependency Injection) and Test with BlocTest, UnitTest, WidgetTest, IntegrationTest
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_sliding_box: ^1.0.5
  dio: ^5.2.1
  retrofit: ^4.0.1
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.1.2
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  dartz: ^0.10.1
  iconsax: ^0.0.8
  file_picker: ^5.3.2
  emoji_picker_flutter: ^1.6.1
  camera: ^0.10.5+2
  rxdart: ^0.27.7
  json_annotation: ^4.8.1
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.5
  retrofit_generator: ^7.0.7
  json_serializable: ^6.7.1
  objectbox_generator: ^2.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.3


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/
    - assets/images/chats/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.otf
    #################################################################
    - family: HelveticaBold
      fonts:
        - asset: assets/fonts/HelveticaBold.ttf
    #################################################################
    - family: LucidaGrande
      fonts:
        - asset: assets/fonts/LucidaGrande.ttf
    #################################################################
    - family: LucidaGrandeBold
      fonts:
        - asset: assets/fonts/LucidaGrandeBold.ttf
    #################################################################
